save_dir: captured_images
save_dir_options:
  - captured_images
  - dataset/captured_images
window:
  width: 1280
  height: 820
  refresh_ms: 40
default_local_ros_ip: 10.192.1.227
robots:
  TRON1:
    ros_version: ros1
    ip: 10.192.1.3
    local_ros_ip: 10.192.1.167
    ros_master_uri_template: http://{robot_ip}:11311
    layout: single
    cameras:
      - key: tron1_camera
        name: TRON1 Camera
        topic: /camera0/color/image_raw
  TRON2:
    ros_version: ros2
    ip: 192.168.1.100
    local_ros_ip: 192.168.1.105
    layout: top_two_bottom
    cameras:
      - key: top
        name: Top Camera
        topic: /camera/top/color/image_raw/compressed
        qos: auto
      - key: left_wrist
        name: Left Wrist Camera
        topic: /camera/left/color/image_resized/compressed
        qos: auto
      - key: right_wrist
        name: Right Wrist Camera
        topic: /camera/right/color/image_resized/compressed
        qos: auto
  bunker:
    ros_version: ros1
    ip: 192.168.1.102
    local_ros_ip: 192.168.1.100
    ros_master_uri_template: http://{robot_ip}:11311
    layout: vertical_two
    cameras:
      - key: base
        name: Base Camera
        topic: /cam_front/color/image_raw
      - key: arm
        name: Arm Camera
        topic: /cam_wrist/color/image_raw
